version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress ## change PASSWORD!!! Use docker secrets or environment virables
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress ## change PASSWORD!!! Use docker secrets or environment virables

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./axenu_theme:/var/www/html/wp-content/themes/AxenuAB
      - ./axenu_plugins:/var/www/html/wp-content/plugins
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress ## change PASSWORD!!! Use docker secrets or environment virables
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
